packages:
  - apps/frontend
  - packages/api-contract

allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': false
  '@swc/core': false
  esbuild: true
  sharp: true
  unrs-resolver: true

overrides:
  postcss: 8.5.28
  sharp: 0.35.4
